### ISSUE TITLE
Detect AU - Sun/NeXT/DEC/UNIX sound file

### ISSUE THREAD

**Issue by odan** [selective-php/audio-type#15]
Au file format

* https://en.wikipedia.org/wiki/Au_file_format

Magic number:
Offset: 0
Value: 0x2e736e64 (four ASCII characters ".snd")

**Comment by peter279k** [comment]
Some useful references are as follows:

- http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/AU/AU.html
- http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/AU/Samples.html

I think this issue should be reopen and fixed :).
