### ISSUE TITLE
Add RealAudio audio file in README.md

### ISSUE THREAD

**Issue by peter279k** [selective-php/audio-type#25]
# Reference

Here is the reference about detecting RealAudio file:

- http://fileformats.archiveteam.org/wiki/RealAudio

**Comment by odan** [comment]
https://github.com/selective-php/audio-type/issues/12

**Comment by peter279k** [comment]
Good. I l almost forget to check PR, but it doesn't include this file support on `README` file.

**Comment by peter279k** [comment]
It should update the supported list on [supported-formats](https://github.com/selective-php/audio-type#supported-formats) section.

**Comment by peter279k** [comment]
According to https://github.com/selective-php/audio-type/pull/18#issuecomment-539014564, it seems the PR is not done.

It's possible to get the audio file and we don't have to create the pseudo file :).
