### ISSUE TITLE
Detect AIF format

### ISSUE THREAD

**Issue by odan** [selective-php/audio-type#7]
Audio Interchange File Format

* https://en.wikipedia.org/wiki/Audio_Interchange_File_Format
* http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/AIFF/Docs/AIFF-1.3.pdf
* http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/AIFF/AIFF.html

**Comment by peter279k** [comment]
I cannot understand why related PR is closed...

**Comment by odan** [comment]
I think because some audio formats, like AIFF, are just outdated ;-)

**Comment by peter279k** [comment]
> I think because some audio formats, like AIFF, are just outdated ;-)

These sample audio files are still available and I will recreate this PR.

**Comment by peter279k** [comment]
@odan, I think it's has been done for https://github.com/selective-php/audio-type/commit/4a628d4c9685cd81e07270c0954fd512ab424451.
